package com.abet.ORM;
//default package
//Generated Mar 2, 2015 12:58:03 AM by Hibernate Tools 3.4.0.CR1
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
* DegreeProgram generated by hbm2java
*/
@Entity
@Table(name = "Degree")
public class Degree {
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id")
	private int id;
	
	@Column(name = "identifier")
	private String identifier;
	
	@Column(name = "description")
	private String description;
	
	@Column(name = "department")
	private String department;

	public Degree() {
	}

	public Degree(int id, String identifier, String department) {
		this.id = id;
		this.identifier = identifier;
		this.department = department;
	}

	public Degree(int id, String identifier, String description,
			String department) {
		this.id = id;
		this.identifier = identifier;
		this.description = description;
		this.department = department;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getIdentifier() {
		return this.identifier;
	}

	public void setIdentifier(String identifier) {
		this.identifier = identifier;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getDepartment() {
		return this.department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}

}
